### ISSUE TITLE
POW issuance underestimation

### ISSUE THREAD

**Issue by MikeSylphDapps** [ultrasoundmoney/frontend#238]
The simulated POW issuance since the merge in EthSupplyWidget and SupplyChange are calculated by [subtracting the POS issuance/day from the POW issuance/day](https://github.com/ultrasoundmoney/frontend/blob/main/src/components/SupplyChange/index.tsx#L23) and [multiplying by the number of slots/day](https://github.com/ultrasoundmoney/frontend/blob/main/src/components/SupplyChange/index.tsx#L45).

Subtracting the two suggests that `powIssuancePerDay` reflects the issuance to both miners and validators during the time when the two chains were running in parallel, but the comment [where the POW issuance per day is declared](https://github.com/ultrasoundmoney/frontend/blob/main/src/static-ether-data.ts#L1) cites https://etherscan.io/chart/blockreward, and their chart only includes issuance from mining.

![image](https://user-images.githubusercontent.com/89714213/198815105-25996817-508e-49e3-a213-63a02dbfdc58.png)

By subtracting the POS issuance from a number that didn't include the POS issuance in the first place, the simulated POW issuance in these two widgets is being underestimated.

It's also worth noting that the [IssuanceGauge](https://github.com/ultrasoundmoney/frontend/blob/main/src/components/Gauges/IssuanceGauge.tsx#L24), the only other component that uses `powIssuancePerDay`, does not subtract the two to find the daily POW issuance.

**Comment by alextes** [comment]
Right. The naming of that constant is terribly confusing 🙈 . I updated it and added a comment. Can you read it and see if that clarifies things well enough?

https://github.com/ultrasoundmoney/frontend/blob/main/src/components/EthSupplyWidget/index.tsx#L45

Thanks for the report!

**Comment by MikeSylphDapps** [comment]
Ahh, I follow now. Thank you for the clarify comment!
