### ISSUE TITLE
Rewrite PriceModel marker rendering

### ISSUE THREAD

**Issue by alextes** [ultrasoundmoney/frontend#249]
<img width="585" alt="Screenshot 2022-11-11 at 11 44 58" src="https://user-images.githubusercontent.com/2011351/201398941-6077b5aa-1630-4cbd-ad73-1cec8299738f.png">

This widget has logos that overlap sometimes, depending on shifts on real-world p/e ratios. It would be nice to rewrite which logos are visible using a system as found in the 200Y projection widget. In short:
* Make an ordered list of markers we have.
* From first to last, only render those markers which do not overlap with any of the markers with a lower index.
* ETH should be first on this list.
* The rest of the companies should be ordered by familiarity with the general public.
* PE ratios sometimes come back null from the API. Skip those.

**Comment by Greg-Johns** [comment]
Hi Alex, here's a take on the PE marker rendering issue.
https://github.com/ultrasoundmoney/frontend/pull/254#issue-1465287175
