### ISSUE TITLE
A quick question about `followed-by`

### ISSUE THREAD

**Issue by fricoben** [ultrasoundmoney/frontend#271]
Hello friends !

Love what you guys are building keep going ! 

I wanted to make section that looks like your "Me and the Fam" section. I wanted to understand how you guys use the Twitter API to see who has or has not the bat signal. I saw that you guys are using this query : `http://localhost:3000/api/fam/fricoben/followed-by`

<img width="518" alt="Capture d’écran 2023-02-27 à 14 36 42" src="https://user-images.githubusercontent.com/78437165/221577853-f168cdee-338a-4b58-9004-ec8be21664c9.png">

Do you have Database for that ? Can someone briefly explain to me how it works cause I can't find any `followed-by` query that can help me. 

Thanks a lot and sorry to disturb you with an issue in your repo. 

You can contact me on Telegram and discord with @fricoben.

**Comment by alextes** [comment]
Issue here is totally fine.

We do have a database. Twitter has an API that lets you ask: who is following account X? The response will include their name and bio. Then we check which accounts have the 🦇🔊 and for those check the followers again. Rinse and repeat. Over many days you can check thousands of accounts.

I can give you access to the backend repo responsible if you'd like to see the code.

**Comment by fricoben** [comment]
I would love to see the code !

**Comment by alextes** [comment]
@fricoben sent you an invite. lmk if you need anything else.
