### ISSUE TITLE
Eth Supply Projection - Dynamic default values for sliders

### ISSUE THREAD

**Issue by ckoopmann** [ultrasoundmoney/frontend#298]
The default / start values for the "Base Gas Price" and "Staking Amount" are currently hard coded to 60 Gwei / 30 M respectively. 
We might want to populate this values dynamically instead based on the latest data. (current values or some kind of projection formula).

![image](https://github.com/ultrasoundmoney/frontend/assets/15629702/c82196fd-8c76-44cc-b1b0-e2afb9efa174)

**Comment by JustinDrake** [comment]
> > We might want to populate this values dynamically instead based on the latest data. (current values or some kind of projection formula).
> 
> Here's how I would do it:
> 
> * **staking amount**: use the current amount (28.7M ETH right now)
> * **base gas price**: as done for the "burn rate" slider in "supply equilibrium" dashboard (see screenshot below), show the average gas price for different time frames (e.g. `all`, `1y`, `30d`) and maybe default to `1y`.
> 
> <img alt="Screenshot 2024-01-16 at 11 04 53" width="952" src="https://private-user-images.githubusercontent.com/731743/297023752-039f326e-718b-4139-a46f-9b8035b3dc72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDM0OTksIm5iZiI6MTcwNTQwMzE5OSwicGF0aCI6Ii83MzE3NDMvMjk3MDIzNzUyLTAzOWYzMjZlLTcxOGItNDEzOS1hNDZmLTliODAzNWIzZGM3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQxMTA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2MxYzNlOWJjNjFlZGU1NDljMTM5MGNlZWJmZDQxNDFlODI1MzFkOTdlOWVmOWJlNTA2Mjc5ODgxODlkZGI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Sg9LrM3iao4O91wqMFHKrFB9DUUNEAY4eeXSPmVPcY">
