### ISSUE TITLE
Burn Categories - Categories undistinguishable in gauge

### ISSUE THREAD

**Issue by ckoopmann** [ultrasoundmoney/frontend#300]
In the burn categories "gauge", the different categories' shares are undistinguishable visually without hovering over one.

We should change that by either:
- Adding separators
- Introducing color scheme

![image](https://github.com/ultrasoundmoney/frontend/assets/15629702/c839260c-2100-4eb8-ad34-4316307abba7)

**Comment by JustinDrake** [comment]
I would lean towards simplicity with an alternating colour scheme :)
