### ISSUE TITLE
Supply Equilibrium - Revisit slider limits

### ISSUE THREAD

**Issue by ckoopmann** [ultrasoundmoney/frontend#304]
The slider limits for the Supply Equilibrium chart are currently:
- Issuance Rewards 2.5 / 5 %
- Burn Rate: 0 / 4.5 %

We should review those values and adjust.

Likely we will want to:
1. Reduce the lower bound on the issuance rewards
2. Reduce the upper bound on the Burn Rate (maybe 3.5%)

![image](https://github.com/ultrasoundmoney/frontend/assets/15629702/5c404b81-7c03-4c5f-bce6-2f8bb9f1bc27)

**Comment by JustinDrake** [comment]
Suggested new values:

* issuance rewards: 2% to 3% (shifting to a more conservative and realistic range)
* burn rate: 0% to 3% (again, a slightly more conservative and realistic range)
