### ISSUE TITLE
New Feature - Flippening Widget

### ISSUE THREAD

**Issue by ckoopmann** [ultrasoundmoney/frontend#313]
Create a new section / set of widgets focusing on eth / btc  price and market cap comparison.

Probably should include a lot of projection features letting people play around with different input parameters and then having a simulation projecting eth / btc market cap / price into the future. 

Open Questions:
- Exact style of visualization.
- Projection algorithm and input parameters
- Focus only market cap flippening or also price flippening ?

**Comment by JustinDrake** [comment]
I'm envisioning an extremely clean chart showing the historical ETH/BTC marketcap ratio, with a logarithmic y-axis. (Everyone focuses on the ETH/BTC price ratio when actually we should be looking at ETH/BTC marketcap ratio.) In terms of style I'm thinking something similar to "ETH supply—200Y projection", i.e. a simple line with a glow effect, no visible x- or y-axis, halo effect background, tooltip on hover.

In addition to the historical logarithmic ETH/BTC marketcap ratio line I would add:

* a point showing the presale (where 2,000 ETH was being sold for 1 BTC and the total marketcap was 72M ETH)
* a horizontal line for the flippening (with a 🐬  emoji somewhere)
* a trend line going from the presale ratio to present day ratio (maybe with a 🦇  emoji somewhere)

**Comment by alextes** [comment]
shipped!
