### ISSUE TITLE
P/E Ratio Data Quality

### ISSUE THREAD

**Issue by rajivpo** [ultrasoundmoney/frontend#340]
The P/E ratios seem to be off relative to what I see elsewhere. Not sure how they're being calculated today, but wanted to flag! Happy to help fix/iterate but couldn't find where the code for `/api/fees/pe-ratios` lives. 

Below is a live response from the endpoint, along with a few spot checks for P/E ratios.

<img width="440" alt="image" src="https://github.com/user-attachments/assets/269cc36e-19eb-458d-81a5-f99dbe64f52a">
<img width="689" alt="Screenshot 2024-09-06 at 2 01 10 PM" src="https://github.com/user-attachments/assets/23b1bc4d-583a-4e15-a9a7-eda0eb7b87f7">
<img width="710" alt="Screenshot 2024-09-06 at 2 01 17 PM" src="https://github.com/user-attachments/assets/c5a83bfb-a823-4489-b84e-703841fde44f">
<img width="723" alt="Screenshot 2024-09-06 at 2 01 32 PM" src="https://github.com/user-attachments/assets/e50f6ff6-16fe-4b34-b62d-193cd0a6bd12">

**Comment by alextes** [comment]
The API key we use to fetch them rotated out from under us, updated the new key, refreshed caches. The website should show the correct markers whenever you full-reload, or local caches expire.

This logic is handled in ultrasoundmoney/eth-analysis-ts which is private. but happy to give you access if you can use it for anything. Although that repo of course doesn't contain the API key that needed updating.

Thanks for reporting! If you ever want to contribute to any of our repos feel free to create another issue or reach out to me t.me/smilingalex (:
