### ISSUE TITLE
Make Blob fee chart scale to current view, not have 0 base always visible

### ISSUE THREAD

**Issue by zymox** [ultrasoundmoney/frontend#345]
The blob fee chart should scale to the current view, like the gas fee chart does.

E.g. looking at this almost horizontal line is quite useless:

![image](https://github.com/user-attachments/assets/565d0ad7-4e97-4d08-b390-9e48ba7d4754)

**Comment by alextes** [comment]
agree, it'd be better if more of the space was used to show changes in the bigger, more meaningful fees than the tiny ones. on the other hand, it'd be a bit confusing if the values on the y-axis were completely different week to week or time frame to time frame. do you have suggestions for how you'd manage the y-axis?

**Comment by zymox** [comment]
Imo it should just behave like the gas fee chart above it, where the minimum on the axis is near the minimum value in the current view, thus including all relevant values in the chart while using all the available screen space.

For example, 5m chart:
![image](https://github.com/user-attachments/assets/96d902dc-43c2-4c7c-a9c5-9a6c9ed3a6b6)

vs.  7d chart:
![image](https://github.com/user-attachments/assets/26a257dd-e63e-4b6a-b95d-e57e86f239d6)

This probably needs to be adjusted a bit to work properly with a log scale, but shouldn't be too hard, no?

**Comment by zymox** [comment]
Noteworthy here too that in the top chart, the max value is 24 only due to the "ultrasound barrier" line needing to be included. No such restriction for the blob fee chart, so in that case it could just show the range of ~12-16 on the axis.

**Comment by alextes** [comment]
@zymox thanks again for the feedback.

updated in 23fb0f0087205c00b6ec9924c80fbae889f0733c
